# Generated by Django 4.2.1 on 2023-05-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('confirm', 'Đã xác nhận'), ('cancel', 'Đã hủy')], max_length=20),
        ),
    ]
