# Generated by Django 4.2.1 on 2023-05-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0002_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
