# Generated by Django 4.2.1 on 2023-05-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0003_remove_product_quantity_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('fish', 'Cá'), ('meat', 'Thịt'), ('vegetable', 'Rau củ trái cây'), ('milk', 'Sữa'), ('drink', 'Đồ uống'), ('noodel', 'Mì gói'), ('snack', 'Bánh kẹo'), ('misc', 'Khác')], default='null', max_length=255),
        ),
    ]
