# Generated by Django 4.2.1 on 2023-05-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0006_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
