# Generated by Django 4.2.1 on 2023-05-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0007_remove_customer_email_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
